name: Deployment - Reusable Workflow
on: 
    workflow_call:

jobs:
    reuse-deploy:
      name: Containerization with Docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Dockerhub login
          uses: docker/login-action@v2.2.0
          with: 
            username: ${{vars.DOCKERHUB_USERNAME}} 
            password: ${{vars. DOCKERHUB_PASSWORD}}

        - name: Docker Build for Testing
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}

        - name: Docker push
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}