name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            nodejs_version: [18,19,20]
            operating_system: [ubuntu-latest,macos-latest]
            exclude:
              - nodejs_version: 18
                operating_system: macos-latest
        runs-on: ${{ matrix.operating_system}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}
        - name: Caching NPM dependencies
          uses: actions/cache@v3

          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
    code-coverage:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
        node-version: 18

     - name: Caching NPM dependencies
       uses: actions/cache@v3

       with:
        path: ~/.npm
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json')}}
     - run: npm install
     - continue-on-error: true
       run: npm run coverage
     - uses: actions/upload-artifact@v4
       with:
        name: Code-Coverage-Result
        path: coverage
        retention-days: 5
        
    docker:
      permissions:
        packages: write
      runs-on: ubuntu-latest
      needs: [unit-testing, code-coverage]
      steps:
        - name: Checkout Code Repository
          uses: actions/checkout@v4
        - uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner}}
            password: ${{secrets.GITHUB_TOKEN}}
        - uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: 'ghcr.io/${{github.repository_owner}}/solar-system:${{github.sha}}'
